### ISSUE TITLE
WebInstall fails on Raspberry Pi

### ISSUE THREAD

**Issue by 1blckhrt** [cococonscious/koji#137]
**Describe the bug**

WebInstall Script for Koji fails on Raspberry Pi. Error message: `mv: cannot stat './koji-*/koji': No such file or directory`

**To Reproduce**

Run the WebInstall Script to attempt to install Koji on a Raspberry Pi system (in my case the 400 model).

**Expected behavior**

I expected the program to install properly and for it to be accessible via terminal.

**Screenshots**

![Image](https://github.com/user-attachments/assets/fb1453eb-02c0-4e4c-b47d-e89bef116f93)

![Image](https://github.com/user-attachments/assets/c9b03bcb-1791-44da-899d-6e729744a753)

**Additional context**

When I attempted to install Koji, I was connecting to the Raspberry Pi via SSH. Unsure if that relates to the problem.
Installing via Cargo worked successfully under the same circumstances.

It appears that all of the directories were indeed created, but not the actual binary itself.

**Comment by 1blckhrt** [comment]
I was able to replicate the issue via WSL and a Linux Mint VM.

**Comment by cococonscious** [comment]
Hi, thanks for your great bug report and replicating it on multiple targets. It seems that I forgot to update the webi install script after changing the build process. The linked PR should solve that issue (at least I hope so, since the webi's test script just wouldn't run on my machine), please report back if possible after your next try!

In the meantime, you can either get the binary directly from the GitHub release (check [this gist](https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8) out if you want to fetch the latest release) or, preferably, install it through cargo. Switching to either of those also has the advantage of not having to trust another third party with installing packages on your systems (or multiple in a sense, since webi modifies your `.bashrc`/`.zshrc`/... for another tool, envman).

**Comment by 1blckhrt** [comment]
Installing via cargo worked completely fine. After running the web install script again, it appears the error persists, and it's now trying to install an entirely different version of Koji from the one in my initial bug report posting. I'm still playing around with Koji as a whole so please correct me if I'm wrong about the version number.

![Image](https://github.com/user-attachments/assets/81f58bf0-2e79-4537-8322-818b21573700)

**Comment by cococonscious** [comment]
The `mv` error should be fixed now, but we're still trying to figure out why it's suddenly taking the wrong version... I'll keep you updated. For now, you can install the latest version explicitly with `curl -Ss https://webinstall.dev/koji@v3.2.0 | bash` if you prefer it over cargo.

**Comment by 1blckhrt** [comment]
Sure, happy to test if need be.
